// Code generated by enthistory, DO NOT EDIT.
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"time"

	"_examples/graphql/ent/testskiphistory"
	"_examples/graphql/ent/todohistory"
	"_examples/graphql/ent/userhistory"

	"entgo.io/ent/dialect/sql"
)

func (_m *TestSkip) History() *TestSkipHistoryQuery {
	historyClient := NewTestSkipHistoryClient(_m.config)
	return historyClient.Query().Where(testskiphistory.Ref(_m.ID))
}

func (_m *TestSkipHistory) Next(ctx context.Context) (*TestSkipHistory, error) {
	client := NewTestSkipHistoryClient(_m.config)
	return client.Query().
		Where(
			testskiphistory.Ref(_m.Ref),
			testskiphistory.HistoryTimeGT(_m.HistoryTime),
		).
		Order(testskiphistory.ByHistoryTime()).
		First(ctx)
}

func (_m *TestSkipHistory) Prev(ctx context.Context) (*TestSkipHistory, error) {
	client := NewTestSkipHistoryClient(_m.config)
	return client.Query().
		Where(
			testskiphistory.Ref(_m.Ref),
			testskiphistory.HistoryTimeLT(_m.HistoryTime),
		).
		Order(testskiphistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (tshq *TestSkipHistoryQuery) Earliest(ctx context.Context) (*TestSkipHistory, error) {
	return tshq.
		Order(testskiphistory.ByHistoryTime()).
		First(ctx)
}

func (tshq *TestSkipHistoryQuery) Latest(ctx context.Context) (*TestSkipHistory, error) {
	return tshq.
		Order(testskiphistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (tshq *TestSkipHistoryQuery) AsOf(ctx context.Context, time time.Time) (*TestSkipHistory, error) {
	return tshq.
		Where(testskiphistory.HistoryTimeLTE(time)).
		Order(testskiphistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (_m *TestSkipHistory) Restore(ctx context.Context) (*TestSkip, error) {
	client := NewTestSkipClient(_m.config)
	return client.
		UpdateOneID(_m.Ref).
		SetOtherID(_m.OtherID).
		SetName(_m.Name).
		Save(ctx)
}

func (_m *Todo) History() *TodoHistoryQuery {
	historyClient := NewTodoHistoryClient(_m.config)
	return historyClient.Query().Where(todohistory.Ref(_m.ID))
}

func (_m *TodoHistory) Next(ctx context.Context) (*TodoHistory, error) {
	client := NewTodoHistoryClient(_m.config)
	return client.Query().
		Where(
			todohistory.Ref(_m.Ref),
			todohistory.HistoryTimeGT(_m.HistoryTime),
		).
		Order(todohistory.ByHistoryTime()).
		First(ctx)
}

func (_m *TodoHistory) Prev(ctx context.Context) (*TodoHistory, error) {
	client := NewTodoHistoryClient(_m.config)
	return client.Query().
		Where(
			todohistory.Ref(_m.Ref),
			todohistory.HistoryTimeLT(_m.HistoryTime),
		).
		Order(todohistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (thq *TodoHistoryQuery) Earliest(ctx context.Context) (*TodoHistory, error) {
	return thq.
		Order(todohistory.ByHistoryTime()).
		First(ctx)
}

func (thq *TodoHistoryQuery) Latest(ctx context.Context) (*TodoHistory, error) {
	return thq.
		Order(todohistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (thq *TodoHistoryQuery) AsOf(ctx context.Context, time time.Time) (*TodoHistory, error) {
	return thq.
		Where(todohistory.HistoryTimeLTE(time)).
		Order(todohistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (_m *TodoHistory) Restore(ctx context.Context) (*Todo, error) {
	client := NewTodoClient(_m.config)
	return client.
		UpdateOneID(_m.Ref).
		SetOtherID(_m.OtherID).
		SetName(_m.Name).
		Save(ctx)
}

func (_m *User) History() *UserHistoryQuery {
	historyClient := NewUserHistoryClient(_m.config)
	return historyClient.Query().Where(userhistory.Ref(_m.ID))
}

func (_m *UserHistory) Next(ctx context.Context) (*UserHistory, error) {
	client := NewUserHistoryClient(_m.config)
	return client.Query().
		Where(
			userhistory.Ref(_m.Ref),
			userhistory.HistoryTimeGT(_m.HistoryTime),
		).
		Order(userhistory.ByHistoryTime()).
		First(ctx)
}

func (_m *UserHistory) Prev(ctx context.Context) (*UserHistory, error) {
	client := NewUserHistoryClient(_m.config)
	return client.Query().
		Where(
			userhistory.Ref(_m.Ref),
			userhistory.HistoryTimeLT(_m.HistoryTime),
		).
		Order(userhistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (uhq *UserHistoryQuery) Earliest(ctx context.Context) (*UserHistory, error) {
	return uhq.
		Order(userhistory.ByHistoryTime()).
		First(ctx)
}

func (uhq *UserHistoryQuery) Latest(ctx context.Context) (*UserHistory, error) {
	return uhq.
		Order(userhistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (uhq *UserHistoryQuery) AsOf(ctx context.Context, time time.Time) (*UserHistory, error) {
	return uhq.
		Where(userhistory.HistoryTimeLTE(time)).
		Order(userhistory.ByHistoryTime(sql.OrderDesc())).
		First(ctx)
}

func (_m *UserHistory) Restore(ctx context.Context) (*User, error) {
	client := NewUserClient(_m.config)
	return client.
		UpdateOneID(_m.Ref).
		SetName(_m.Name).
		SetEmail(_m.Email).
		Save(ctx)
}
