// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_examples/graphql/ent/predicate"
	"_examples/graphql/ent/testexclude"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TestExcludeUpdate is the builder for updating TestExclude entities.
type TestExcludeUpdate struct {
	config
	hooks    []Hook
	mutation *TestExcludeMutation
}

// Where appends a list predicates to the TestExcludeUpdate builder.
func (_u *TestExcludeUpdate) Where(ps ...predicate.TestExclude) *TestExcludeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOtherID sets the "other_id" field.
func (_u *TestExcludeUpdate) SetOtherID(v uuid.UUID) *TestExcludeUpdate {
	_u.mutation.SetOtherID(v)
	return _u
}

// SetNillableOtherID sets the "other_id" field if the given value is not nil.
func (_u *TestExcludeUpdate) SetNillableOtherID(v *uuid.UUID) *TestExcludeUpdate {
	if v != nil {
		_u.SetOtherID(*v)
	}
	return _u
}

// ClearOtherID clears the value of the "other_id" field.
func (_u *TestExcludeUpdate) ClearOtherID() *TestExcludeUpdate {
	_u.mutation.ClearOtherID()
	return _u
}

// SetName sets the "name" field.
func (_u *TestExcludeUpdate) SetName(v string) *TestExcludeUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TestExcludeUpdate) SetNillableName(v *string) *TestExcludeUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the TestExcludeMutation object of the builder.
func (_u *TestExcludeUpdate) Mutation() *TestExcludeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TestExcludeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestExcludeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TestExcludeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestExcludeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestExcludeUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := testexclude.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TestExclude.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TestExcludeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testexclude.Table, testexclude.Columns, sqlgraph.NewFieldSpec(testexclude.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OtherID(); ok {
		_spec.SetField(testexclude.FieldOtherID, field.TypeUUID, value)
	}
	if _u.mutation.OtherIDCleared() {
		_spec.ClearField(testexclude.FieldOtherID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(testexclude.FieldName, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testexclude.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TestExcludeUpdateOne is the builder for updating a single TestExclude entity.
type TestExcludeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TestExcludeMutation
}

// SetOtherID sets the "other_id" field.
func (_u *TestExcludeUpdateOne) SetOtherID(v uuid.UUID) *TestExcludeUpdateOne {
	_u.mutation.SetOtherID(v)
	return _u
}

// SetNillableOtherID sets the "other_id" field if the given value is not nil.
func (_u *TestExcludeUpdateOne) SetNillableOtherID(v *uuid.UUID) *TestExcludeUpdateOne {
	if v != nil {
		_u.SetOtherID(*v)
	}
	return _u
}

// ClearOtherID clears the value of the "other_id" field.
func (_u *TestExcludeUpdateOne) ClearOtherID() *TestExcludeUpdateOne {
	_u.mutation.ClearOtherID()
	return _u
}

// SetName sets the "name" field.
func (_u *TestExcludeUpdateOne) SetName(v string) *TestExcludeUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TestExcludeUpdateOne) SetNillableName(v *string) *TestExcludeUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// Mutation returns the TestExcludeMutation object of the builder.
func (_u *TestExcludeUpdateOne) Mutation() *TestExcludeMutation {
	return _u.mutation
}

// Where appends a list predicates to the TestExcludeUpdate builder.
func (_u *TestExcludeUpdateOne) Where(ps ...predicate.TestExclude) *TestExcludeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TestExcludeUpdateOne) Select(field string, fields ...string) *TestExcludeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TestExclude entity.
func (_u *TestExcludeUpdateOne) Save(ctx context.Context) (*TestExclude, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TestExcludeUpdateOne) SaveX(ctx context.Context) *TestExclude {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TestExcludeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TestExcludeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TestExcludeUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := testexclude.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TestExclude.name": %w`, err)}
		}
	}
	return nil
}

func (_u *TestExcludeUpdateOne) sqlSave(ctx context.Context) (_node *TestExclude, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(testexclude.Table, testexclude.Columns, sqlgraph.NewFieldSpec(testexclude.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TestExclude.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, testexclude.FieldID)
		for _, f := range fields {
			if !testexclude.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != testexclude.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OtherID(); ok {
		_spec.SetField(testexclude.FieldOtherID, field.TypeUUID, value)
	}
	if _u.mutation.OtherIDCleared() {
		_spec.ClearField(testexclude.FieldOtherID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(testexclude.FieldName, field.TypeString, value)
	}
	_node = &TestExclude{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{testexclude.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
