// Code generated by ent, DO NOT EDIT.

package testskip

import (
	"_examples/graphql/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldLTE(FieldID, id))
}

// OtherID applies equality check predicate on the "other_id" field. It's identical to OtherIDEQ.
func OtherID(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEQ(FieldOtherID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEQ(FieldName, v))
}

// OtherIDEQ applies the EQ predicate on the "other_id" field.
func OtherIDEQ(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEQ(FieldOtherID, v))
}

// OtherIDNEQ applies the NEQ predicate on the "other_id" field.
func OtherIDNEQ(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNEQ(FieldOtherID, v))
}

// OtherIDIn applies the In predicate on the "other_id" field.
func OtherIDIn(vs ...uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldIn(FieldOtherID, vs...))
}

// OtherIDNotIn applies the NotIn predicate on the "other_id" field.
func OtherIDNotIn(vs ...uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNotIn(FieldOtherID, vs...))
}

// OtherIDGT applies the GT predicate on the "other_id" field.
func OtherIDGT(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldGT(FieldOtherID, v))
}

// OtherIDGTE applies the GTE predicate on the "other_id" field.
func OtherIDGTE(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldGTE(FieldOtherID, v))
}

// OtherIDLT applies the LT predicate on the "other_id" field.
func OtherIDLT(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldLT(FieldOtherID, v))
}

// OtherIDLTE applies the LTE predicate on the "other_id" field.
func OtherIDLTE(v uuid.UUID) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldLTE(FieldOtherID, v))
}

// OtherIDIsNil applies the IsNil predicate on the "other_id" field.
func OtherIDIsNil() predicate.TestSkip {
	return predicate.TestSkip(sql.FieldIsNull(FieldOtherID))
}

// OtherIDNotNil applies the NotNil predicate on the "other_id" field.
func OtherIDNotNil() predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNotNull(FieldOtherID))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TestSkip {
	return predicate.TestSkip(sql.FieldContainsFold(FieldName, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TestSkip) predicate.TestSkip {
	return predicate.TestSkip(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TestSkip) predicate.TestSkip {
	return predicate.TestSkip(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TestSkip) predicate.TestSkip {
	return predicate.TestSkip(sql.NotPredicates(p))
}
