// Code generated by enthistory, DO NOT EDIT.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent"

	"github.com/flume/enthistory"

	"github.com/google/uuid"
)

var (
	idNotFoundError = errors.New("could not get id from mutation")
)

func EntOpToHistoryOp(op ent.Op) enthistory.OpType {
	switch op {
	case ent.OpDelete, ent.OpDeleteOne:
		return enthistory.OpTypeDelete
	case ent.OpUpdate, ent.OpUpdateOne:
		return enthistory.OpTypeUpdate
	default:
		return enthistory.OpTypeInsert
	}
}

func rollback(tx *Tx, err error) error {
	if tx != nil {
		if rerr := tx.Rollback(); rerr != nil {
			err = fmt.Errorf("%w: %v", err, rerr)
		}
		return err
	}
	return err
}

func (m *MenuItemMutation) CreateHistoryFromCreate(ctx context.Context) error {
	client := m.Client()
	tx, err := m.Tx()
	if err != nil {
		tx = nil
	}

	updatedBy, _ := ctx.Value("userId").(uuid.UUID)

	id, ok := m.ID()
	if !ok {
		return rollback(tx, idNotFoundError)
	}

	create := client.MenuItemHistory.Create()
	if tx != nil {
		create = tx.MenuItemHistory.Create()
	}

	create = create.
		SetOperation(EntOpToHistoryOp(m.Op())).
		SetHistoryTime(time.Now()).
		SetRef(id)
	if updatedBy != uuid.Nil {
		create = create.SetUpdatedBy(updatedBy)
	}

	if createdAt, exists := m.CreatedAt(); exists {
		create = create.SetCreatedAt(createdAt)
	}

	if updatedAt, exists := m.UpdatedAt(); exists {
		create = create.SetUpdatedAt(updatedAt)
	}

	if name, exists := m.Name(); exists {
		create = create.SetName(name)
	}

	if price, exists := m.Price(); exists {
		create = create.SetPrice(price)
	}

	if description, exists := m.Description(); exists {
		create = create.SetDescription(description)
	}

	_, err = create.Save(ctx)
	if err != nil {
		rollback(tx, err)
	}
	return nil
}

func (m *MenuItemMutation) CreateHistoryFromUpdate(ctx context.Context) error {
	client := m.Client()
	tx, err := m.Tx()
	if err != nil {
		tx = nil
	}

	updatedBy, _ := ctx.Value("userId").(uuid.UUID)

	ids, err := m.IDs(ctx)
	if err != nil {
		return rollback(tx, fmt.Errorf("getting ids: %w", err))
	}

	for _, id := range ids {
		menuitem, err := client.MenuItem.Get(ctx, id)
		if err != nil {
			return rollback(tx, err)
		}

		create := client.MenuItemHistory.Create()
		if tx != nil {
			create = tx.MenuItemHistory.Create()
		}

		create = create.
			SetOperation(EntOpToHistoryOp(m.Op())).
			SetHistoryTime(time.Now()).
			SetRef(id)
		if updatedBy != uuid.Nil {
			create = create.SetUpdatedBy(updatedBy)
		}

		if createdAt, exists := m.CreatedAt(); exists {
			create = create.SetCreatedAt(createdAt)
		} else {
			create = create.SetCreatedAt(menuitem.CreatedAt)
		}

		if updatedAt, exists := m.UpdatedAt(); exists {
			create = create.SetUpdatedAt(updatedAt)
		} else {
			create = create.SetUpdatedAt(menuitem.UpdatedAt)
		}

		if name, exists := m.Name(); exists {
			create = create.SetName(name)
		} else {
			create = create.SetName(menuitem.Name)
		}

		if price, exists := m.Price(); exists {
			create = create.SetPrice(price)
		} else {
			create = create.SetPrice(menuitem.Price)
		}

		if description, exists := m.Description(); exists {
			create = create.SetDescription(description)
		} else {
			create = create.SetDescription(menuitem.Description)
		}

		_, err = create.Save(ctx)
		if err != nil {
			rollback(tx, err)
		}
	}

	return nil
}

func (m *MenuItemMutation) CreateHistoryFromDelete(ctx context.Context) error {
	client := m.Client()
	tx, err := m.Tx()
	if err != nil {
		tx = nil
	}

	updatedBy, _ := ctx.Value("userId").(uuid.UUID)

	ids, err := m.IDs(ctx)
	if err != nil {
		return rollback(tx, fmt.Errorf("getting ids: %w", err))
	}

	for _, id := range ids {
		menuitem, err := client.MenuItem.Get(ctx, id)
		if err != nil {
			return rollback(tx, err)
		}

		create := client.MenuItemHistory.Create()
		if tx != nil {
			create = tx.MenuItemHistory.Create()
		}
		if updatedBy != uuid.Nil {
			create = create.SetUpdatedBy(updatedBy)
		}

		_, err = create.
			SetOperation(EntOpToHistoryOp(m.Op())).
			SetHistoryTime(time.Now()).
			SetRef(id).
			SetCreatedAt(menuitem.CreatedAt).
			SetUpdatedAt(menuitem.UpdatedAt).
			SetName(menuitem.Name).
			SetPrice(menuitem.Price).
			SetDescription(menuitem.Description).
			Save(ctx)
		if err != nil {
			rollback(tx, err)
		}
	}

	return nil
}
