// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MenuItemColumns holds the columns for the "menu_item" table.
	MenuItemColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// MenuItemTable holds the schema information for the "menu_item" table.
	MenuItemTable = &schema.Table{
		Name:       "menu_item",
		Columns:    MenuItemColumns,
		PrimaryKey: []*schema.Column{MenuItemColumns[0]},
	}
	// MenuItemHistoryColumns holds the columns for the "menu_item_history" table.
	MenuItemHistoryColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "history_time", Type: field.TypeTime},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"INSERT", "UPDATE", "DELETE"}},
		{Name: "ref", Type: field.TypeUUID, Nullable: true},
		{Name: "updated_by", Type: field.TypeUUID, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// MenuItemHistoryTable holds the schema information for the "menu_item_history" table.
	MenuItemHistoryTable = &schema.Table{
		Name:       "menu_item_history",
		Columns:    MenuItemHistoryColumns,
		PrimaryKey: []*schema.Column{MenuItemHistoryColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "menuitemhistory_history_time",
				Unique:  false,
				Columns: []*schema.Column{MenuItemHistoryColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MenuItemTable,
		MenuItemHistoryTable,
	}
)

func init() {
	MenuItemTable.Annotation = &entsql.Annotation{
		Table: "menu_item",
	}
	MenuItemHistoryTable.Annotation = &entsql.Annotation{
		Table: "menu_item_history",
	}
}
