// Code generated by enthistory, DO NOT EDIT.
// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"time"

	"github.com/flume/enthistory/_examples/ent/characterhistory"
	"github.com/flume/enthistory/_examples/ent/friendshiphistory"
)

func (ch *CharacterHistory) Restore(ctx context.Context) (*Character, error) {
	client := NewCharacterClient(ch.config)
	return client.
		UpdateOneID(ch.Ref).
		SetUpdatedAt(ch.UpdatedAt).
		SetAge(ch.Age).
		SetName(ch.Name).
		Save(ctx)
}

func (c *Character) History() *CharacterHistoryQuery {
	historyClient := NewCharacterHistoryClient(c.config)
	return historyClient.Query().Where(characterhistory.Ref(c.ID))
}

func (chq *CharacterHistoryQuery) Earliest(ctx context.Context) (*CharacterHistory, error) {
	return chq.
		Order(Asc(characterhistory.FieldHistoryTime)).
		First(ctx)
}

func (chq *CharacterHistoryQuery) Latest(ctx context.Context) (*CharacterHistory, error) {
	return chq.
		Order(Desc(characterhistory.FieldHistoryTime)).
		First(ctx)
}

func (chq *CharacterHistoryQuery) AsOf(ctx context.Context, time time.Time) (*CharacterHistory, error) {
	return chq.
		Where(characterhistory.HistoryTimeLTE(time)).
		Order(Desc(characterhistory.FieldHistoryTime)).
		First(ctx)
}

func (fh *FriendshipHistory) Restore(ctx context.Context) (*Friendship, error) {
	client := NewFriendshipClient(fh.config)
	return client.
		UpdateOneID(fh.Ref).
		SetUpdatedAt(fh.UpdatedAt).
		SetCharacterID(fh.CharacterID).
		SetFriendID(fh.FriendID).
		Save(ctx)
}

func (f *Friendship) History() *FriendshipHistoryQuery {
	historyClient := NewFriendshipHistoryClient(f.config)
	return historyClient.Query().Where(friendshiphistory.Ref(f.ID))
}

func (fhq *FriendshipHistoryQuery) Earliest(ctx context.Context) (*FriendshipHistory, error) {
	return fhq.
		Order(Asc(friendshiphistory.FieldHistoryTime)).
		First(ctx)
}

func (fhq *FriendshipHistoryQuery) Latest(ctx context.Context) (*FriendshipHistory, error) {
	return fhq.
		Order(Desc(friendshiphistory.FieldHistoryTime)).
		First(ctx)
}

func (fhq *FriendshipHistoryQuery) AsOf(ctx context.Context, time time.Time) (*FriendshipHistory, error) {
	return fhq.
		Where(friendshiphistory.HistoryTimeLTE(time)).
		Order(Desc(friendshiphistory.FieldHistoryTime)).
		First(ctx)
}
