// Code generated by enthistory, DO NOT EDIT.

package otherschema

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"github.com/flume/enthistory"
)

type CharacterHistory struct {
	ent.Schema
}

func (CharacterHistory) Fields() []ent.Field {
	return []ent.Field{
		field.Int("id").
			Immutable(),
		field.Time("history_time").
			Immutable().
			Default(time.Now),
		field.Enum("operation").
			Immutable().
			GoType(enthistory.OpType("")),
		field.UUID("ref", uuid.UUID{}).
			Optional().
			Immutable(),
		field.Int("age"),
		field.String("name")}
}
func (CharacterHistory) Edges() []ent.Edge {
	return nil
}
func (CharacterHistory) Annotations() []schema.Annotation {
	return []schema.Annotation{entsql.Annotation{Table: "character_history"}}
}
