// Code generated by enthistory, DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"

	"github.com/frisbm/enthistory"

	"time"
)

// UserHistory holds the schema definition for the UserHistory entity.
type UserHistory struct {
	ent.Schema
}

// Annotations of the UserHistory.
func (UserHistory) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.Annotation{
			Table: "user_history",
		},
	}
}

// Fields of the UserHistory.
func (UserHistory) Fields() []ent.Field {
	historyFields := []ent.Field{
		field.Time("history_time").
			Default(time.Now).
			UpdateDefault(time.Now),
		field.Int("ref").
			Optional(),
		field.String("updated_by").
			Optional().
			Nillable(),
		field.Enum("operation").GoType(enthistory.OpType("")),
	}

	return append(historyFields, User{}.Fields()...)
}

// Mixin of the UserHistory.
func (UserHistory) Mixin() []ent.Mixin {
	return User{}.Mixin()
}
