// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Character is the predicate function for character builders.
type Character func(*sql.Selector)

// CharacterHistory is the predicate function for characterhistory builders.
type CharacterHistory func(*sql.Selector)

// Friendship is the predicate function for friendship builders.
type Friendship func(*sql.Selector)

// FriendshipHistory is the predicate function for friendshiphistory builders.
type FriendshipHistory func(*sql.Selector)
