// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_examples/basic/ent/character"
	"_examples/basic/ent/friendship"
	"_examples/basic/ent/predicate"
	"_examples/basic/ent/residence"
	"_examples/basic/ent/schema/models"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// CharacterUpdate is the builder for updating Character entities.
type CharacterUpdate struct {
	config
	hooks    []Hook
	mutation *CharacterMutation
}

// Where appends a list predicates to the CharacterUpdate builder.
func (_u *CharacterUpdate) Where(ps ...predicate.Character) *CharacterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CharacterUpdate) SetUpdatedAt(v time.Time) *CharacterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAge sets the "age" field.
func (_u *CharacterUpdate) SetAge(v int) *CharacterUpdate {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableAge(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *CharacterUpdate) AddAge(v int) *CharacterUpdate {
	_u.mutation.AddAge(v)
	return _u
}

// SetTypedAge sets the "typed_age" field.
func (_u *CharacterUpdate) SetTypedAge(v models.Uint64) *CharacterUpdate {
	_u.mutation.ResetTypedAge()
	_u.mutation.SetTypedAge(v)
	return _u
}

// SetNillableTypedAge sets the "typed_age" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableTypedAge(v *models.Uint64) *CharacterUpdate {
	if v != nil {
		_u.SetTypedAge(*v)
	}
	return _u
}

// AddTypedAge adds value to the "typed_age" field.
func (_u *CharacterUpdate) AddTypedAge(v models.Uint64) *CharacterUpdate {
	_u.mutation.AddTypedAge(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CharacterUpdate) SetName(v string) *CharacterUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableName(v *string) *CharacterUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNicknames sets the "nicknames" field.
func (_u *CharacterUpdate) SetNicknames(v []string) *CharacterUpdate {
	_u.mutation.SetNicknames(v)
	return _u
}

// AppendNicknames appends value to the "nicknames" field.
func (_u *CharacterUpdate) AppendNicknames(v []string) *CharacterUpdate {
	_u.mutation.AppendNicknames(v)
	return _u
}

// ClearNicknames clears the value of the "nicknames" field.
func (_u *CharacterUpdate) ClearNicknames() *CharacterUpdate {
	_u.mutation.ClearNicknames()
	return _u
}

// SetInfo sets the "info" field.
func (_u *CharacterUpdate) SetInfo(v map[string]interface{}) *CharacterUpdate {
	_u.mutation.SetInfo(v)
	return _u
}

// ClearInfo clears the value of the "info" field.
func (_u *CharacterUpdate) ClearInfo() *CharacterUpdate {
	_u.mutation.ClearInfo()
	return _u
}

// SetInfoStruct sets the "info_struct" field.
func (_u *CharacterUpdate) SetInfoStruct(v models.InfoStruct) *CharacterUpdate {
	_u.mutation.SetInfoStruct(v)
	return _u
}

// SetNillableInfoStruct sets the "info_struct" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableInfoStruct(v *models.InfoStruct) *CharacterUpdate {
	if v != nil {
		_u.SetInfoStruct(*v)
	}
	return _u
}

// ClearInfoStruct clears the value of the "info_struct" field.
func (_u *CharacterUpdate) ClearInfoStruct() *CharacterUpdate {
	_u.mutation.ClearInfoStruct()
	return _u
}

// SetLevel sets the "level" field.
func (_u *CharacterUpdate) SetLevel(v int) *CharacterUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableLevel(v *int) *CharacterUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *CharacterUpdate) AddLevel(v int) *CharacterUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *CharacterUpdate) ClearLevel() *CharacterUpdate {
	_u.mutation.ClearLevel()
	return _u
}

// SetSpecies sets the "species" field.
func (_u *CharacterUpdate) SetSpecies(v models.SpeciesType) *CharacterUpdate {
	_u.mutation.SetSpecies(v)
	return _u
}

// SetNillableSpecies sets the "species" field if the given value is not nil.
func (_u *CharacterUpdate) SetNillableSpecies(v *models.SpeciesType) *CharacterUpdate {
	if v != nil {
		_u.SetSpecies(*v)
	}
	return _u
}

// ClearSpecies clears the value of the "species" field.
func (_u *CharacterUpdate) ClearSpecies() *CharacterUpdate {
	_u.mutation.ClearSpecies()
	return _u
}

// AddFriendIDs adds the "friends" edge to the Character entity by IDs.
func (_u *CharacterUpdate) AddFriendIDs(ids ...int) *CharacterUpdate {
	_u.mutation.AddFriendIDs(ids...)
	return _u
}

// AddFriends adds the "friends" edges to the Character entity.
func (_u *CharacterUpdate) AddFriends(v ...*Character) *CharacterUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFriendIDs(ids...)
}

// SetResidenceID sets the "residence" edge to the Residence entity by ID.
func (_u *CharacterUpdate) SetResidenceID(id uuid.UUID) *CharacterUpdate {
	_u.mutation.SetResidenceID(id)
	return _u
}

// SetNillableResidenceID sets the "residence" edge to the Residence entity by ID if the given value is not nil.
func (_u *CharacterUpdate) SetNillableResidenceID(id *uuid.UUID) *CharacterUpdate {
	if id != nil {
		_u = _u.SetResidenceID(*id)
	}
	return _u
}

// SetResidence sets the "residence" edge to the Residence entity.
func (_u *CharacterUpdate) SetResidence(v *Residence) *CharacterUpdate {
	return _u.SetResidenceID(v.ID)
}

// AddFriendshipIDs adds the "friendships" edge to the Friendship entity by IDs.
func (_u *CharacterUpdate) AddFriendshipIDs(ids ...string) *CharacterUpdate {
	_u.mutation.AddFriendshipIDs(ids...)
	return _u
}

// AddFriendships adds the "friendships" edges to the Friendship entity.
func (_u *CharacterUpdate) AddFriendships(v ...*Friendship) *CharacterUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFriendshipIDs(ids...)
}

// Mutation returns the CharacterMutation object of the builder.
func (_u *CharacterUpdate) Mutation() *CharacterMutation {
	return _u.mutation
}

// ClearFriends clears all "friends" edges to the Character entity.
func (_u *CharacterUpdate) ClearFriends() *CharacterUpdate {
	_u.mutation.ClearFriends()
	return _u
}

// RemoveFriendIDs removes the "friends" edge to Character entities by IDs.
func (_u *CharacterUpdate) RemoveFriendIDs(ids ...int) *CharacterUpdate {
	_u.mutation.RemoveFriendIDs(ids...)
	return _u
}

// RemoveFriends removes "friends" edges to Character entities.
func (_u *CharacterUpdate) RemoveFriends(v ...*Character) *CharacterUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFriendIDs(ids...)
}

// ClearResidence clears the "residence" edge to the Residence entity.
func (_u *CharacterUpdate) ClearResidence() *CharacterUpdate {
	_u.mutation.ClearResidence()
	return _u
}

// ClearFriendships clears all "friendships" edges to the Friendship entity.
func (_u *CharacterUpdate) ClearFriendships() *CharacterUpdate {
	_u.mutation.ClearFriendships()
	return _u
}

// RemoveFriendshipIDs removes the "friendships" edge to Friendship entities by IDs.
func (_u *CharacterUpdate) RemoveFriendshipIDs(ids ...string) *CharacterUpdate {
	_u.mutation.RemoveFriendshipIDs(ids...)
	return _u
}

// RemoveFriendships removes "friendships" edges to Friendship entities.
func (_u *CharacterUpdate) RemoveFriendships(v ...*Friendship) *CharacterUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFriendshipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CharacterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CharacterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CharacterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := character.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CharacterUpdate) check() error {
	if v, ok := _u.mutation.Age(); ok {
		if err := character.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "Character.age": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypedAge(); ok {
		if err := character.TypedAgeValidator(uint64(v)); err != nil {
			return &ValidationError{Name: "typed_age", err: fmt.Errorf(`ent: validator failed for field "Character.typed_age": %w`, err)}
		}
	}
	return nil
}

func (_u *CharacterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(character.Table, character.Columns, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(character.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(character.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(character.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TypedAge(); ok {
		_spec.SetField(character.FieldTypedAge, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTypedAge(); ok {
		_spec.AddField(character.FieldTypedAge, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nicknames(); ok {
		_spec.SetField(character.FieldNicknames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNicknames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, character.FieldNicknames, value)
		})
	}
	if _u.mutation.NicknamesCleared() {
		_spec.ClearField(character.FieldNicknames, field.TypeJSON)
	}
	if value, ok := _u.mutation.Info(); ok {
		_spec.SetField(character.FieldInfo, field.TypeJSON, value)
	}
	if _u.mutation.InfoCleared() {
		_spec.ClearField(character.FieldInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.InfoStruct(); ok {
		_spec.SetField(character.FieldInfoStruct, field.TypeJSON, value)
	}
	if _u.mutation.InfoStructCleared() {
		_spec.ClearField(character.FieldInfoStruct, field.TypeJSON)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(character.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(character.FieldLevel, field.TypeInt, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(character.FieldLevel, field.TypeInt)
	}
	if value, ok := _u.mutation.Species(); ok {
		_spec.SetField(character.FieldSpecies, field.TypeString, value)
	}
	if _u.mutation.SpeciesCleared() {
		_spec.ClearField(character.FieldSpecies, field.TypeString)
	}
	if _u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   character.FriendsTable,
			Columns: character.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		createE := &FriendshipCreate{config: _u.config, mutation: newFriendshipMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFriendsIDs(); len(nodes) > 0 && !_u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   character.FriendsTable,
			Columns: character.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FriendshipCreate{config: _u.config, mutation: newFriendshipMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FriendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   character.FriendsTable,
			Columns: character.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FriendshipCreate{config: _u.config, mutation: newFriendshipMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.ResidenceTable,
			Columns: []string{character.ResidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(residence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.ResidenceTable,
			Columns: []string{character.ResidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(residence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FriendshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   character.FriendshipsTable,
			Columns: []string{character.FriendshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(friendship.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFriendshipsIDs(); len(nodes) > 0 && !_u.mutation.FriendshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   character.FriendshipsTable,
			Columns: []string{character.FriendshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(friendship.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FriendshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   character.FriendshipsTable,
			Columns: []string{character.FriendshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(friendship.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{character.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CharacterUpdateOne is the builder for updating a single Character entity.
type CharacterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CharacterMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CharacterUpdateOne) SetUpdatedAt(v time.Time) *CharacterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAge sets the "age" field.
func (_u *CharacterUpdateOne) SetAge(v int) *CharacterUpdateOne {
	_u.mutation.ResetAge()
	_u.mutation.SetAge(v)
	return _u
}

// SetNillableAge sets the "age" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableAge(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetAge(*v)
	}
	return _u
}

// AddAge adds value to the "age" field.
func (_u *CharacterUpdateOne) AddAge(v int) *CharacterUpdateOne {
	_u.mutation.AddAge(v)
	return _u
}

// SetTypedAge sets the "typed_age" field.
func (_u *CharacterUpdateOne) SetTypedAge(v models.Uint64) *CharacterUpdateOne {
	_u.mutation.ResetTypedAge()
	_u.mutation.SetTypedAge(v)
	return _u
}

// SetNillableTypedAge sets the "typed_age" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableTypedAge(v *models.Uint64) *CharacterUpdateOne {
	if v != nil {
		_u.SetTypedAge(*v)
	}
	return _u
}

// AddTypedAge adds value to the "typed_age" field.
func (_u *CharacterUpdateOne) AddTypedAge(v models.Uint64) *CharacterUpdateOne {
	_u.mutation.AddTypedAge(v)
	return _u
}

// SetName sets the "name" field.
func (_u *CharacterUpdateOne) SetName(v string) *CharacterUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableName(v *string) *CharacterUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetNicknames sets the "nicknames" field.
func (_u *CharacterUpdateOne) SetNicknames(v []string) *CharacterUpdateOne {
	_u.mutation.SetNicknames(v)
	return _u
}

// AppendNicknames appends value to the "nicknames" field.
func (_u *CharacterUpdateOne) AppendNicknames(v []string) *CharacterUpdateOne {
	_u.mutation.AppendNicknames(v)
	return _u
}

// ClearNicknames clears the value of the "nicknames" field.
func (_u *CharacterUpdateOne) ClearNicknames() *CharacterUpdateOne {
	_u.mutation.ClearNicknames()
	return _u
}

// SetInfo sets the "info" field.
func (_u *CharacterUpdateOne) SetInfo(v map[string]interface{}) *CharacterUpdateOne {
	_u.mutation.SetInfo(v)
	return _u
}

// ClearInfo clears the value of the "info" field.
func (_u *CharacterUpdateOne) ClearInfo() *CharacterUpdateOne {
	_u.mutation.ClearInfo()
	return _u
}

// SetInfoStruct sets the "info_struct" field.
func (_u *CharacterUpdateOne) SetInfoStruct(v models.InfoStruct) *CharacterUpdateOne {
	_u.mutation.SetInfoStruct(v)
	return _u
}

// SetNillableInfoStruct sets the "info_struct" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableInfoStruct(v *models.InfoStruct) *CharacterUpdateOne {
	if v != nil {
		_u.SetInfoStruct(*v)
	}
	return _u
}

// ClearInfoStruct clears the value of the "info_struct" field.
func (_u *CharacterUpdateOne) ClearInfoStruct() *CharacterUpdateOne {
	_u.mutation.ClearInfoStruct()
	return _u
}

// SetLevel sets the "level" field.
func (_u *CharacterUpdateOne) SetLevel(v int) *CharacterUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableLevel(v *int) *CharacterUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *CharacterUpdateOne) AddLevel(v int) *CharacterUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// ClearLevel clears the value of the "level" field.
func (_u *CharacterUpdateOne) ClearLevel() *CharacterUpdateOne {
	_u.mutation.ClearLevel()
	return _u
}

// SetSpecies sets the "species" field.
func (_u *CharacterUpdateOne) SetSpecies(v models.SpeciesType) *CharacterUpdateOne {
	_u.mutation.SetSpecies(v)
	return _u
}

// SetNillableSpecies sets the "species" field if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableSpecies(v *models.SpeciesType) *CharacterUpdateOne {
	if v != nil {
		_u.SetSpecies(*v)
	}
	return _u
}

// ClearSpecies clears the value of the "species" field.
func (_u *CharacterUpdateOne) ClearSpecies() *CharacterUpdateOne {
	_u.mutation.ClearSpecies()
	return _u
}

// AddFriendIDs adds the "friends" edge to the Character entity by IDs.
func (_u *CharacterUpdateOne) AddFriendIDs(ids ...int) *CharacterUpdateOne {
	_u.mutation.AddFriendIDs(ids...)
	return _u
}

// AddFriends adds the "friends" edges to the Character entity.
func (_u *CharacterUpdateOne) AddFriends(v ...*Character) *CharacterUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFriendIDs(ids...)
}

// SetResidenceID sets the "residence" edge to the Residence entity by ID.
func (_u *CharacterUpdateOne) SetResidenceID(id uuid.UUID) *CharacterUpdateOne {
	_u.mutation.SetResidenceID(id)
	return _u
}

// SetNillableResidenceID sets the "residence" edge to the Residence entity by ID if the given value is not nil.
func (_u *CharacterUpdateOne) SetNillableResidenceID(id *uuid.UUID) *CharacterUpdateOne {
	if id != nil {
		_u = _u.SetResidenceID(*id)
	}
	return _u
}

// SetResidence sets the "residence" edge to the Residence entity.
func (_u *CharacterUpdateOne) SetResidence(v *Residence) *CharacterUpdateOne {
	return _u.SetResidenceID(v.ID)
}

// AddFriendshipIDs adds the "friendships" edge to the Friendship entity by IDs.
func (_u *CharacterUpdateOne) AddFriendshipIDs(ids ...string) *CharacterUpdateOne {
	_u.mutation.AddFriendshipIDs(ids...)
	return _u
}

// AddFriendships adds the "friendships" edges to the Friendship entity.
func (_u *CharacterUpdateOne) AddFriendships(v ...*Friendship) *CharacterUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFriendshipIDs(ids...)
}

// Mutation returns the CharacterMutation object of the builder.
func (_u *CharacterUpdateOne) Mutation() *CharacterMutation {
	return _u.mutation
}

// ClearFriends clears all "friends" edges to the Character entity.
func (_u *CharacterUpdateOne) ClearFriends() *CharacterUpdateOne {
	_u.mutation.ClearFriends()
	return _u
}

// RemoveFriendIDs removes the "friends" edge to Character entities by IDs.
func (_u *CharacterUpdateOne) RemoveFriendIDs(ids ...int) *CharacterUpdateOne {
	_u.mutation.RemoveFriendIDs(ids...)
	return _u
}

// RemoveFriends removes "friends" edges to Character entities.
func (_u *CharacterUpdateOne) RemoveFriends(v ...*Character) *CharacterUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFriendIDs(ids...)
}

// ClearResidence clears the "residence" edge to the Residence entity.
func (_u *CharacterUpdateOne) ClearResidence() *CharacterUpdateOne {
	_u.mutation.ClearResidence()
	return _u
}

// ClearFriendships clears all "friendships" edges to the Friendship entity.
func (_u *CharacterUpdateOne) ClearFriendships() *CharacterUpdateOne {
	_u.mutation.ClearFriendships()
	return _u
}

// RemoveFriendshipIDs removes the "friendships" edge to Friendship entities by IDs.
func (_u *CharacterUpdateOne) RemoveFriendshipIDs(ids ...string) *CharacterUpdateOne {
	_u.mutation.RemoveFriendshipIDs(ids...)
	return _u
}

// RemoveFriendships removes "friendships" edges to Friendship entities.
func (_u *CharacterUpdateOne) RemoveFriendships(v ...*Friendship) *CharacterUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFriendshipIDs(ids...)
}

// Where appends a list predicates to the CharacterUpdate builder.
func (_u *CharacterUpdateOne) Where(ps ...predicate.Character) *CharacterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CharacterUpdateOne) Select(field string, fields ...string) *CharacterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Character entity.
func (_u *CharacterUpdateOne) Save(ctx context.Context) (*Character, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CharacterUpdateOne) SaveX(ctx context.Context) *Character {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CharacterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CharacterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CharacterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := character.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CharacterUpdateOne) check() error {
	if v, ok := _u.mutation.Age(); ok {
		if err := character.AgeValidator(v); err != nil {
			return &ValidationError{Name: "age", err: fmt.Errorf(`ent: validator failed for field "Character.age": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TypedAge(); ok {
		if err := character.TypedAgeValidator(uint64(v)); err != nil {
			return &ValidationError{Name: "typed_age", err: fmt.Errorf(`ent: validator failed for field "Character.typed_age": %w`, err)}
		}
	}
	return nil
}

func (_u *CharacterUpdateOne) sqlSave(ctx context.Context) (_node *Character, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(character.Table, character.Columns, sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Character.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, character.FieldID)
		for _, f := range fields {
			if !character.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != character.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(character.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Age(); ok {
		_spec.SetField(character.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAge(); ok {
		_spec.AddField(character.FieldAge, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TypedAge(); ok {
		_spec.SetField(character.FieldTypedAge, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTypedAge(); ok {
		_spec.AddField(character.FieldTypedAge, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(character.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nicknames(); ok {
		_spec.SetField(character.FieldNicknames, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedNicknames(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, character.FieldNicknames, value)
		})
	}
	if _u.mutation.NicknamesCleared() {
		_spec.ClearField(character.FieldNicknames, field.TypeJSON)
	}
	if value, ok := _u.mutation.Info(); ok {
		_spec.SetField(character.FieldInfo, field.TypeJSON, value)
	}
	if _u.mutation.InfoCleared() {
		_spec.ClearField(character.FieldInfo, field.TypeJSON)
	}
	if value, ok := _u.mutation.InfoStruct(); ok {
		_spec.SetField(character.FieldInfoStruct, field.TypeJSON, value)
	}
	if _u.mutation.InfoStructCleared() {
		_spec.ClearField(character.FieldInfoStruct, field.TypeJSON)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(character.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(character.FieldLevel, field.TypeInt, value)
	}
	if _u.mutation.LevelCleared() {
		_spec.ClearField(character.FieldLevel, field.TypeInt)
	}
	if value, ok := _u.mutation.Species(); ok {
		_spec.SetField(character.FieldSpecies, field.TypeString, value)
	}
	if _u.mutation.SpeciesCleared() {
		_spec.ClearField(character.FieldSpecies, field.TypeString)
	}
	if _u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   character.FriendsTable,
			Columns: character.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		createE := &FriendshipCreate{config: _u.config, mutation: newFriendshipMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFriendsIDs(); len(nodes) > 0 && !_u.mutation.FriendsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   character.FriendsTable,
			Columns: character.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FriendshipCreate{config: _u.config, mutation: newFriendshipMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FriendsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   character.FriendsTable,
			Columns: character.FriendsPrimaryKey,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &FriendshipCreate{config: _u.config, mutation: newFriendshipMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ResidenceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.ResidenceTable,
			Columns: []string{character.ResidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(residence.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   character.ResidenceTable,
			Columns: []string{character.ResidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(residence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FriendshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   character.FriendshipsTable,
			Columns: []string{character.FriendshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(friendship.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFriendshipsIDs(); len(nodes) > 0 && !_u.mutation.FriendshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   character.FriendshipsTable,
			Columns: []string{character.FriendshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(friendship.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FriendshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   character.FriendshipsTable,
			Columns: []string{character.FriendshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(friendship.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Character{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{character.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
