// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_examples/basic/ent/friendshiphistory"
	"_examples/basic/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendshipHistoryUpdate is the builder for updating FriendshipHistory entities.
type FriendshipHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *FriendshipHistoryMutation
}

// Where appends a list predicates to the FriendshipHistoryUpdate builder.
func (_u *FriendshipHistoryUpdate) Where(ps ...predicate.FriendshipHistory) *FriendshipHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FriendshipHistoryUpdate) SetUpdatedAt(v time.Time) *FriendshipHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FriendshipHistoryMutation object of the builder.
func (_u *FriendshipHistoryUpdate) Mutation() *FriendshipHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FriendshipHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FriendshipHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FriendshipHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FriendshipHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FriendshipHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := friendshiphistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FriendshipHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(friendshiphistory.Table, friendshiphistory.Columns, sqlgraph.NewFieldSpec(friendshiphistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(friendshiphistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(friendshiphistory.FieldRef, field.TypeString)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(friendshiphistory.FieldUpdatedBy, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{friendshiphistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FriendshipHistoryUpdateOne is the builder for updating a single FriendshipHistory entity.
type FriendshipHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FriendshipHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FriendshipHistoryUpdateOne) SetUpdatedAt(v time.Time) *FriendshipHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the FriendshipHistoryMutation object of the builder.
func (_u *FriendshipHistoryUpdateOne) Mutation() *FriendshipHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the FriendshipHistoryUpdate builder.
func (_u *FriendshipHistoryUpdateOne) Where(ps ...predicate.FriendshipHistory) *FriendshipHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FriendshipHistoryUpdateOne) Select(field string, fields ...string) *FriendshipHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FriendshipHistory entity.
func (_u *FriendshipHistoryUpdateOne) Save(ctx context.Context) (*FriendshipHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FriendshipHistoryUpdateOne) SaveX(ctx context.Context) *FriendshipHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FriendshipHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FriendshipHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FriendshipHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := friendshiphistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *FriendshipHistoryUpdateOne) sqlSave(ctx context.Context) (_node *FriendshipHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(friendshiphistory.Table, friendshiphistory.Columns, sqlgraph.NewFieldSpec(friendshiphistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FriendshipHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendshiphistory.FieldID)
		for _, f := range fields {
			if !friendshiphistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != friendshiphistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(friendshiphistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(friendshiphistory.FieldRef, field.TypeString)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(friendshiphistory.FieldUpdatedBy, field.TypeInt)
	}
	_node = &FriendshipHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{friendshiphistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
