// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_examples/basic/ent/predicate"
	"_examples/basic/ent/residencehistory"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ResidenceHistoryDelete is the builder for deleting a ResidenceHistory entity.
type ResidenceHistoryDelete struct {
	config
	hooks    []Hook
	mutation *ResidenceHistoryMutation
}

// Where appends a list predicates to the ResidenceHistoryDelete builder.
func (_d *ResidenceHistoryDelete) Where(ps ...predicate.ResidenceHistory) *ResidenceHistoryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ResidenceHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResidenceHistoryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ResidenceHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(residencehistory.Table, sqlgraph.NewFieldSpec(residencehistory.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ResidenceHistoryDeleteOne is the builder for deleting a single ResidenceHistory entity.
type ResidenceHistoryDeleteOne struct {
	_d *ResidenceHistoryDelete
}

// Where appends a list predicates to the ResidenceHistoryDelete builder.
func (_d *ResidenceHistoryDeleteOne) Where(ps ...predicate.ResidenceHistory) *ResidenceHistoryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ResidenceHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{residencehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ResidenceHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
