// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_examples/basic/ent/residence"
	"_examples/basic/ent/residencehistory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"

	"github.com/flume/enthistory"
)

// ResidenceHistoryCreate is the builder for creating a ResidenceHistory entity.
type ResidenceHistoryCreate struct {
	config
	mutation *ResidenceHistoryMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResidenceHistoryCreate) SetCreatedAt(v time.Time) *ResidenceHistoryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResidenceHistoryCreate) SetNillableCreatedAt(v *time.Time) *ResidenceHistoryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ResidenceHistoryCreate) SetUpdatedAt(v time.Time) *ResidenceHistoryCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ResidenceHistoryCreate) SetNillableUpdatedAt(v *time.Time) *ResidenceHistoryCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetHistoryTime sets the "history_time" field.
func (_c *ResidenceHistoryCreate) SetHistoryTime(v time.Time) *ResidenceHistoryCreate {
	_c.mutation.SetHistoryTime(v)
	return _c
}

// SetNillableHistoryTime sets the "history_time" field if the given value is not nil.
func (_c *ResidenceHistoryCreate) SetNillableHistoryTime(v *time.Time) *ResidenceHistoryCreate {
	if v != nil {
		_c.SetHistoryTime(*v)
	}
	return _c
}

// SetOperation sets the "operation" field.
func (_c *ResidenceHistoryCreate) SetOperation(v enthistory.OpType) *ResidenceHistoryCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetRef sets the "ref" field.
func (_c *ResidenceHistoryCreate) SetRef(v uuid.UUID) *ResidenceHistoryCreate {
	_c.mutation.SetRef(v)
	return _c
}

// SetNillableRef sets the "ref" field if the given value is not nil.
func (_c *ResidenceHistoryCreate) SetNillableRef(v *uuid.UUID) *ResidenceHistoryCreate {
	if v != nil {
		_c.SetRef(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ResidenceHistoryCreate) SetUpdatedBy(v int) *ResidenceHistoryCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ResidenceHistoryCreate) SetNillableUpdatedBy(v *int) *ResidenceHistoryCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ResidenceHistoryCreate) SetName(v string) *ResidenceHistoryCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ResidenceHistoryCreate) SetID(v int) *ResidenceHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetResidenceID sets the "residence" edge to the Residence entity by ID.
func (_c *ResidenceHistoryCreate) SetResidenceID(id uuid.UUID) *ResidenceHistoryCreate {
	_c.mutation.SetResidenceID(id)
	return _c
}

// SetNillableResidenceID sets the "residence" edge to the Residence entity by ID if the given value is not nil.
func (_c *ResidenceHistoryCreate) SetNillableResidenceID(id *uuid.UUID) *ResidenceHistoryCreate {
	if id != nil {
		_c = _c.SetResidenceID(*id)
	}
	return _c
}

// SetResidence sets the "residence" edge to the Residence entity.
func (_c *ResidenceHistoryCreate) SetResidence(v *Residence) *ResidenceHistoryCreate {
	return _c.SetResidenceID(v.ID)
}

// Mutation returns the ResidenceHistoryMutation object of the builder.
func (_c *ResidenceHistoryCreate) Mutation() *ResidenceHistoryMutation {
	return _c.mutation
}

// Save creates the ResidenceHistory in the database.
func (_c *ResidenceHistoryCreate) Save(ctx context.Context) (*ResidenceHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResidenceHistoryCreate) SaveX(ctx context.Context) *ResidenceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResidenceHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResidenceHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResidenceHistoryCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := residencehistory.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := residencehistory.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.HistoryTime(); !ok {
		v := residencehistory.DefaultHistoryTime()
		_c.mutation.SetHistoryTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResidenceHistoryCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResidenceHistory.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ResidenceHistory.updated_at"`)}
	}
	if _, ok := _c.mutation.HistoryTime(); !ok {
		return &ValidationError{Name: "history_time", err: errors.New(`ent: missing required field "ResidenceHistory.history_time"`)}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "ResidenceHistory.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := residencehistory.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "ResidenceHistory.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ResidenceHistory.name"`)}
	}
	return nil
}

func (_c *ResidenceHistoryCreate) sqlSave(ctx context.Context) (*ResidenceHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResidenceHistoryCreate) createSpec() (*ResidenceHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &ResidenceHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(residencehistory.Table, sqlgraph.NewFieldSpec(residencehistory.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(residencehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(residencehistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.HistoryTime(); ok {
		_spec.SetField(residencehistory.FieldHistoryTime, field.TypeTime, value)
		_node.HistoryTime = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(residencehistory.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Ref(); ok {
		_spec.SetField(residencehistory.FieldRef, field.TypeUUID, value)
		_node.Ref = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(residencehistory.FieldUpdatedBy, field.TypeInt, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(residencehistory.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := _c.mutation.ResidenceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   residencehistory.ResidenceTable,
			Columns: []string{residencehistory.ResidenceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(residence.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.residence_history_residence = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResidenceHistoryCreateBulk is the builder for creating many ResidenceHistory entities in bulk.
type ResidenceHistoryCreateBulk struct {
	config
	err      error
	builders []*ResidenceHistoryCreate
}

// Save creates the ResidenceHistory entities in the database.
func (_c *ResidenceHistoryCreateBulk) Save(ctx context.Context) ([]*ResidenceHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResidenceHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResidenceHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResidenceHistoryCreateBulk) SaveX(ctx context.Context) []*ResidenceHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResidenceHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResidenceHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
