// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"github.com/flume/enthistory/_examples/updateby_uuid/ent/organizationhistory"
	"github.com/flume/enthistory/_examples/updateby_uuid/ent/predicate"
)

// OrganizationHistoryDelete is the builder for deleting a OrganizationHistory entity.
type OrganizationHistoryDelete struct {
	config
	hooks    []Hook
	mutation *OrganizationHistoryMutation
}

// Where appends a list predicates to the OrganizationHistoryDelete builder.
func (ohd *OrganizationHistoryDelete) Where(ps ...predicate.OrganizationHistory) *OrganizationHistoryDelete {
	ohd.mutation.Where(ps...)
	return ohd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ohd *OrganizationHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ohd.sqlExec, ohd.mutation, ohd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ohd *OrganizationHistoryDelete) ExecX(ctx context.Context) int {
	n, err := ohd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ohd *OrganizationHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(organizationhistory.Table, sqlgraph.NewFieldSpec(organizationhistory.FieldID, field.TypeInt))
	if ps := ohd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ohd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ohd.mutation.done = true
	return affected, err
}

// OrganizationHistoryDeleteOne is the builder for deleting a single OrganizationHistory entity.
type OrganizationHistoryDeleteOne struct {
	ohd *OrganizationHistoryDelete
}

// Where appends a list predicates to the OrganizationHistoryDelete builder.
func (ohdo *OrganizationHistoryDeleteOne) Where(ps ...predicate.OrganizationHistory) *OrganizationHistoryDeleteOne {
	ohdo.ohd.mutation.Where(ps...)
	return ohdo
}

// Exec executes the deletion query.
func (ohdo *OrganizationHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := ohdo.ohd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{organizationhistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ohdo *OrganizationHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := ohdo.Exec(ctx); err != nil {
		panic(err)
	}
}
