// Code generated by ent, DO NOT EDIT.

package ent

import (
	"_examples/updateby_uuid/ent/predicate"
	"_examples/updateby_uuid/ent/storehistory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StoreHistoryUpdate is the builder for updating StoreHistory entities.
type StoreHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *StoreHistoryMutation
}

// Where appends a list predicates to the StoreHistoryUpdate builder.
func (_u *StoreHistoryUpdate) Where(ps ...predicate.StoreHistory) *StoreHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StoreHistoryUpdate) SetUpdatedAt(v time.Time) *StoreHistoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *StoreHistoryUpdate) SetName(v string) *StoreHistoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StoreHistoryUpdate) SetNillableName(v *string) *StoreHistoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *StoreHistoryUpdate) SetRegion(v string) *StoreHistoryUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *StoreHistoryUpdate) SetNillableRegion(v *string) *StoreHistoryUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *StoreHistoryUpdate) SetOrganizationID(v uuid.UUID) *StoreHistoryUpdate {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *StoreHistoryUpdate) SetNillableOrganizationID(v *uuid.UUID) *StoreHistoryUpdate {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// Mutation returns the StoreHistoryMutation object of the builder.
func (_u *StoreHistoryUpdate) Mutation() *StoreHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StoreHistoryUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StoreHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StoreHistoryUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storehistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StoreHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(storehistory.Table, storehistory.Columns, sqlgraph.NewFieldSpec(storehistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(storehistory.FieldRef, field.TypeUUID)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(storehistory.FieldUpdatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(storehistory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(storehistory.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(storehistory.FieldOrganizationID, field.TypeUUID, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StoreHistoryUpdateOne is the builder for updating a single StoreHistory entity.
type StoreHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreHistoryMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StoreHistoryUpdateOne) SetUpdatedAt(v time.Time) *StoreHistoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *StoreHistoryUpdateOne) SetName(v string) *StoreHistoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StoreHistoryUpdateOne) SetNillableName(v *string) *StoreHistoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *StoreHistoryUpdateOne) SetRegion(v string) *StoreHistoryUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *StoreHistoryUpdateOne) SetNillableRegion(v *string) *StoreHistoryUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetOrganizationID sets the "organization_id" field.
func (_u *StoreHistoryUpdateOne) SetOrganizationID(v uuid.UUID) *StoreHistoryUpdateOne {
	_u.mutation.SetOrganizationID(v)
	return _u
}

// SetNillableOrganizationID sets the "organization_id" field if the given value is not nil.
func (_u *StoreHistoryUpdateOne) SetNillableOrganizationID(v *uuid.UUID) *StoreHistoryUpdateOne {
	if v != nil {
		_u.SetOrganizationID(*v)
	}
	return _u
}

// Mutation returns the StoreHistoryMutation object of the builder.
func (_u *StoreHistoryUpdateOne) Mutation() *StoreHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the StoreHistoryUpdate builder.
func (_u *StoreHistoryUpdateOne) Where(ps ...predicate.StoreHistory) *StoreHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StoreHistoryUpdateOne) Select(field string, fields ...string) *StoreHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StoreHistory entity.
func (_u *StoreHistoryUpdateOne) Save(ctx context.Context) (*StoreHistory, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreHistoryUpdateOne) SaveX(ctx context.Context) *StoreHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StoreHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StoreHistoryUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := storehistory.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *StoreHistoryUpdateOne) sqlSave(ctx context.Context) (_node *StoreHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(storehistory.Table, storehistory.Columns, sqlgraph.NewFieldSpec(storehistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StoreHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storehistory.FieldID)
		for _, f := range fields {
			if !storehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(storehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RefCleared() {
		_spec.ClearField(storehistory.FieldRef, field.TypeUUID)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(storehistory.FieldUpdatedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(storehistory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(storehistory.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.OrganizationID(); ok {
		_spec.SetField(storehistory.FieldOrganizationID, field.TypeUUID, value)
	}
	_node = &StoreHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
