// Code generated by enthistory, DO NOT EDIT.
package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/google/uuid"

	"github.com/flume/enthistory"

	"time"
)

// ResidenceHistory holds the schema definition for the ResidenceHistory entity.
type ResidenceHistory struct {
	ent.Schema
}

// Annotations of the ResidenceHistory.
func (ResidenceHistory) Annotations() []schema.Annotation {
	tablename := "residence_history"
	annotations := append(Residence{}.Annotations(), enthistory.Annotations{
		IsHistory: true,
		Exclude:   true,
	})
	for i, a := range annotations {
		if ant, ok := a.(entsql.Annotation); ok {
			ant.Table = tablename
			annotations[i] = ant
			break
		}
		if i == len(annotations)-1 {
			annotations = append(annotations, entsql.Annotation{Table: tablename})
		}
	}
	return annotations
}

// Fields of the ResidenceHistory.
func (ResidenceHistory) Fields() []ent.Field {
	historyFields := []ent.Field{
		field.Time("history_time").
			Default(time.Now).
			Immutable(),
		field.UUID("ref", uuid.UUID{}).
			Immutable().
			Optional(),
		field.Enum("operation").
			GoType(enthistory.OpType("")).
			Immutable(),
		field.Int("updated_by").
			Optional().
			Immutable().
			Nillable(),
	}

	original := Residence{}
	for _, field := range original.Fields() {
		if field.Descriptor().Name != "id" {
			historyFields = append(historyFields, field)
		}
	}

	return historyFields
}

// Mixin of the ResidenceHistory.
func (ResidenceHistory) Mixin() []ent.Mixin {
	return Residence{}.Mixin()
}
func (ResidenceHistory) Indexes() []ent.Index {
	return []ent.Index{
		index.Fields("history_time"),
	}
}
