name: Testing

on:
  push:
    branches:
      - '**' # Run on all branches
      - '!main' # Except main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: go.mod
          go-version: '1.20'

      - name: Test
        run: go test ./_examples/.

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: go.mod
          go-version: '1.20'

      - name: GoLang CI Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout 10m0s
          skip-cache: true

  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          cache: true
          cache-dependency-path: go.mod
          go-version: '1.20'

      - name: Format
        run: |
          go install golang.org/x/tools/cmd/goimports@v0.9.3
          UNFORMATTED_CODE_GOFMT=$(goimports -local github.com/flume -d ./)
